json.id @data[:id]
json.name @data[:name]
json.quantity @data[:quantity]

json.energy_kcal @data[:energy_kcal]
json.protein @data[:protein]
json.fat @data[:fat]
json.carbon @data[:carbon]
json.vitaminA @data[:vitaminA]
json.vitaminB1 @data[:vitaminB1]
json.vitaminC @data[:vitaminC]
json.calcium @data[:calcium]
json.dietaryFiber @data[:dietary_fiber]
json.salt @data[:salt]
